version: 1.0.{build}
os: Visual Studio 2015
platform: Any CPU
configuration: Release

branches:
  only:
    - release

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore
  - ps: cd InstagramApi
  - ps: dotnet --verbose build
  - ps: dotnet --verbose pack -o ../nugetpack -c release
  - ps: cd ../InstagramApi.Tests
  - ps: dotnet restore
  - ps: dotnet --verbose build
  - ps: dotnet --verbose test
  - ps: cd ..

assembly_info:
  patch: true
  file: project.json
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

deploy:
  - provider: GitHub
    auth_token:
      secure: FE6k4kAwz++t3+H7UvZkUELVZsx8DIjSOM1R3ZVT7YgqwQXuMKFQpDM5HmQobF22
    artifact: '**\*.nupkg', InstagramApi\bin\release\netstandard1.6\*.dll
    draft: false
    prerelease: true
    on:
      branch: release
  - provider: NuGet
    api_key:
      secure: At3FDhivtW6bQz/WXdwE6RzuFeouCMag3htqBE/1uuTJnFmHB8hU9gCy31ORFWtS
    artifact: '**\*.nupkg'
test: off
