version: 1.0.{build}
os: Visual Studio 2015
platform: Any CPU
configuration: Release

branches:
  only:
    - release

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore
  - ps: cd InstagramApi
  - ps: dotnet --verbose build
  - ps: dotnet --verbose pack
  - ps: cd ../InstagramApi.Tests
  - ps: dotnet restore
  - ps: dotnet --verbose build
  - ps: dotnet --verbose test
  - ps: cd ..

assembly_info:
  patch: true
  file: project.json
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

environment:
  git_access_token:
    secure: rgNPj4/9Qv2wWDiq1a/IBZmwR1QAvL181hj707JArmQUyTROThxqGfbB4OPyvfeu

deploy:
  - provider: GitHub
    auth_token:
      secure: FE6k4kAwz++t3+H7UvZkUELVZsx8DIjSOM1R3ZVT7YgqwQXuMKFQpDM5HmQobF22
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: release                # release from master branch only
test: off
